name: Update
on:
  schedule:
    - cron: '0 15 * * *'
  push:
    
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oror-sine/Velog-gql-JSON-schema
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install requirements.txt
        run:  pip install -r requirements.txt

      - run: |
          chmod +x ./script.sh
          ./script.sh